### ISSUE TITLE
Become Active Contributor - roadmap?

### ISSUE THREAD

**Issue by evolmk** [WiziShop/ng-wizi-bulma#16]
Hi, great work on your components so far, i switched to Bulma (from bootstrap) last year and haven't looked back.

I can submit PR's and ask them to be merged correct?  I'll be using your component in my new app, and i'll build/extend features as i need them

**Is there a Roadmap or new features you'd like me to work on?**

thanks!

**Comment by JumBay** [comment]
Hi,

Sorry for the late late answer, we've missed your issue...

There is no roadmap for the moment, we're adding components because we need them for our app. 

PR are welcome if you want to extend/bug fixes the lib.

Thanks
