### ISSUE TITLE
Datepicker showClearButton property

### ISSUE THREAD

**Issue by alecrt** [WiziShop/ng-wizi-bulma#21]
Is showClearButton property working?

I set it to false, but i still found the clear button in the datetimepicker-dummy-wrapper.

And Thanks: I love bulma and I love Angular: so this library is awesome!

**Comment by JumBay** [comment]
It does work, I updated the demo with an example of it (first datepicker): https://ng-wizi-bulma.firebaseapp.com/date-picker

**Comment by alecrt** [comment]
There was a misunderstood. I was talking about the rotate X in the right corner of the inline container.

Da: Jean-Baptiste Malatrasi <notifications@github.com>
Inviato: mercoledì 15 aprile 2020 12:29
A: WiziShop/ng-wizi-bulma <ng-wizi-bulma@noreply.github.com>
Cc: alecrt <alessandrocurti@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [WiziShop/ng-wizi-bulma] Datepicker showClearButton property (#21)


It does work, I updated the demo with an example of it (first datepicker): https://ng-wizi-bulma.firebaseapp.com/date-picker<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fng-wizi-bulma.firebaseapp.com%2Fdate-picker&data=02%7C01%7C%7Cdbab9b7236554cba050a08d7e127d28a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637225433453911664&sdata=vLWbuLFGiR%2BvzRmTtaR4rx54FzaiDS9L6zsRJd10%2F0U%3D&reserved=0>
