### ISSUE TITLE
Responsive dialog

### ISSUE THREAD

**Issue by Smiley01987** [WiziShop/ng-wizi-bulma#5]
Hi,

Is there any way to make the dialog responsive?

**Comment by Anakior** [comment]
Hi, 

I will look into it.

There is some issue with the integration.

**Comment by Smiley01987** [comment]
Great, thanks for the quick reply!

I was also wondering if its also possible to close the modal programmatically?
Here's a small example of what i mean;

1. User clicks on login button on home screen
2. Login button triggers function that opens the modal (openFromComponent LoginComponent)
3. Login successful, close modal from within LoginComponent

Maybe something based on id's?

Thanks in advance!

**Comment by Anakior** [comment]
Responsive is back on modal with last version.

@JumBay will respond to your question when he have time since he have done the modal ;)

**Comment by JumBay** [comment]
Hi @Smiley01987,

I think what you want it's exactly what is done in the [code](https://github.com/WiziShop/ng-wizi-bulma/blob/master/src/demo-app/features/dialog/dialog-demo.ts#L47) of the first dialog exemple : https://ng-wizi-bulma.firebaseapp.com/dialog: `Simple Dialog with custom handler function on ok (yes) button`

You can configure an custom handler method on click on the OK button, and dismiss the dialog from there: 
```ts
let dialog = this.nwbDialog.open(this.dialogConfig); //Open the dialog

dialog.config.okHandler = () => { // On click on the OK button do your own login logic here
   dialog.disableButtonsAndMakeOkButtonLoading(); 

   // Your login method
   this.myLoginMethodYouHaveToImplement()
   .subscribe(()=>{
        dialog.enableButtonsAndMakeOkButtonNotLoading();
        dialog.dismiss(true); // Close the dialog
   })
};
