### ISSUE TITLE
Tab support

### ISSUE THREAD

**Issue by redbaty** [WiziShop/ng-wizi-bulma#6]
It would be great if this had a tab wrapper, that automatically switched contents

**Comment by JumBay** [comment]
We should think about it. If you have any suggestion on how it should works let's us know.
We could check out how material handle it https://material.angular.io/components/tabs/overview

**Comment by redbaty** [comment]
@JumBay  Yup, [Buefy also implements it](https://buefy.github.io/#/documentation/tabs)

**Comment by TomzOk** [comment]
I sent a PR for tabs.  No worried if you don't merge I had this from another project and just copied it here and renamed some things to match.  Thanks for lib.  Would  be nice to have the Buefy table for angular next.

**Comment by JumBay** [comment]
PR merged
